name: 'check docs'

on:
  pull_request:
    branches:
      - main
  
jobs:
  check_sphinx_docs:
    name: Check Sphinx Docs
    runs-on: ubuntu-latest
    steps:
    - uses: neuroinformatics-unit/actions/check_sphinx_docs@v1.2.0
